### PR TITLE
Added tag-keys and tag-values api

### PR DESCRIPTION
**Pull request by DracoBlue**
Since we need adHocFilters (tag-keys + tag-values api) in one of our projects, we extended the simple-json-datasource to provide also those values from the http json api.

This little PR adds this functionality to the official grafana simple-json-datasource plugin.

### CODE REVIEW

**Comment by DracoBlue** [comment]
I added tests and also generated dist. If something is missing (e.g. for @daniellee), tell me and I'll update the PR!

**Comment by tcolgate** [comment]
Would it make sense to allow retrieval of hte operators too? I need this myself but our internal logging system can support "=","~","!=" and "!~" operators.

**Comment by DracoBlue** [comment]
The operators are part of the query:

```
  "adhocFilters": [
    "key": "City"
    "operator": "=",
    "value": "Berlin"
  ]
```

In my case I map those to the equivalents of the datasource.

But having those retrievable would be nice! I will see how this can be achieved.

**Comment by daniellee** [comment]
Thanks @DracoBlue - works great.

**Comment by DracoBlue** [comment]
You are welcome.

**Pull request merged**
