### PR TITLE
Pass additional json data

### PR DESCRIPTION
**Pull request by simPod**
Built on top of https://github.com/grafana/simple-json-datasource/pull/103

Adds another field to targets setup, that allows to pass additional json data with target

### CODE REVIEW

**Comment by andig** [comment]
@simPod I couldn't find out immediately- where can I find the additional json option? Per Panel??

**Comment by andig** [comment]
This one?

screen shot 2018-07-23 at 22 56 22

Should I enter a json object here? 

Alternatively- might it make sense to allow selecting tags/values? Must admit that I haven't found where Grafana actually uses the tag keys/values api :/

**Comment by simPod** [comment]
Yup, that one is for entering your json you want to add to the request.

Not sure how tags/values are related here. Can you be more specific please? I made this column to pass additional data to the request.

For example, my use case is that I control Grafana via API, that means I specify all dashboards and panels via objects and then just run the sync command to synchronize the schema. The panels definition is therefore shared through dashboards but for different dashboards, I want the panels to make slightly different requests and that is achieved by configuring this field per dashboard if needed.

**Comment by andig** [comment]
I've meanwhile tested and its working like a charm. The thing I don't like so much is the UI- a very small, non-obvious text field. I had two ideas:

  - use the tags/values (that a datasource can provide or that you can define manually per dashboard) and allow passing tags+tag values per query (would look cleaner, I'd be happy to share a screenshot)
  - modify the data field into something like a button (maybe `{json}`) and a larger popup for enterying (plus syntax check if you want)

I can understand if that doesn't sound attractive given zero feedback :(

**Comment by simPod** [comment]
Yup, the UI sucks but I didn't want to pimp it without any feedback from repo maintainers.

I can't imagine the tags/values, can you share the screenshot? Larger field was something I rather had on my mind.

**Comment by andig** [comment]
> I can't imagine the tags/values, can you share the screenshot

Sorry for the delay. 

Here are the tags- manual definition (if not supplied by the json data source)- UI. 

screen shot 2018-08-03 at 16 32 47

Selection UI on dashboard level:

screen shot 2018-08-03 at 16 32 22

That UI might be something that could be done per panel in the settings to override dashboard-wide tags or define additional ones?

Here's how the json looks, it becomes part of the target:

	{
	  "timezone": "browser",
	  "panelId": 6,
	  "dashboardId": 1,

	  "targets": [
	    {
	      "target": "19f2ef70-d39e-11e7-b2e8-f552c3dac8a7",
	      "data": {
	        "mode": "consumption",
	        "group": "hour"
	      },
	      "refId": "A",
	      "type": "timeseries"
	    },
	    {
	      "target": "0f746430-d39e-11e7-9f92-2f38b410ecdc",
	      "data": {
	        "mode": "consumption",
	        "group": "hour"
	      },
	      "refId": "B",
	      "type": "timeseries"
	    }
	  ],
	  "maxDataPoints": 1152,

	  "adhocFilters": []
	}

**Comment by simPod** [comment]
Personally, I didn't want to lock it to dashboard-defined variables only, I wanted the full flexibility so for me the second option is viable

> modify the data field into something like a button (maybe {json}) and a larger popup for enterying (plus syntax check if you want)

But since [no one still cares](https://community.grafana.com/t/roadmap-of-simple-json-datasource-plugin/9123) I'll wait ;)

**Comment by andig** [comment]
> But since no one still cares I'll wait ;)

Yeah :( I've been wondering if you might consider a "hard" fork and publish `grafana-json` on your own? It's MIT license and I'd appreciate a working version more than months-old PRs :)

Btw., I have another use case for a JSON plugin: extract definable parts from arbitrary JSON sources. That is- instead of talking to a grafana-conforming json source- talk to any JSON endpoint and define patterns for extracting metrics, annotations and data. The forecast.io API might be a good candicate for that. WDYT?

**Comment by andig** [comment]
> Personally, I didn't want to lock it to dashboard-defined variables only, I wanted the full flexibility so for me the second option is viable

And I forgot to mention that tags/values (=dashboard variables) are retrievable using the JSON datasource through the `tags-keys|values` api.

**Comment by simPod** [comment]
@andig maybe having both options would work as well 🤔 

@daniellee @DanCech @bergquist Hi, trying a one more ping so we know the repository is abandonded by Grafana Labs or not. Thanks!

**Comment by andig** [comment]
@simPod I finally discovered this but couldn't get it working immediately- maybe you'd want to take another look: https://github.com/grafana/grafana/blob/d2cdacce40a1547b4798b2f66ff3e410cfbbebef/public/app/partials/edit_json.html#L14

**Comment by simPod** [comment]
I'll try to take a look @ it asap

**Comment by andig** [comment]
Here are the component's [docs](https://github.com/grafana/grafana/blob/master/public/app/core/components/code_editor/code_editor.ts). I still think it would be nice if we could also expose tags and values as dropdown options per panal for transfer in `data.tags`.

**Comment by andig** [comment]
@simPod finally got it working- you could use this [gist]( https://gist.github.com/andig/3c56e680f53c4a0f5f4d9c0e5a8c1e94). 

Still need to ensure though that data is not null:

        this.target.data = this.target.data || "";

Would be great to omit data from the query if it's json amounts to an empty string.

**Comment by andig** [comment]
This PR has been migrated to https://github.com/simPod/grafana-json-datasource and can be closed.

**Comment by daniellee** [comment]
@andig @simPod I am also not really sure if we want this PR in SimpleJson so maybe it is best if you focus on your datasource. Once you get to the stage where you need an extra json field then it usually gets specific to what you are building and in my experience is time to fork this into a new plugin. I will double check with my team on what they think about this.

We can publish https://github.com/simPod/grafana-json-datasource on Grafana.com if you want.

**Comment by simPod** [comment]
Yup, for me as well. I control Grafana via it's API, I define dashboard and panel models in PHP and don't even use any Edit interface within Grafana.

Additional JSON field allows me to parametrize Panels data per dashboard, sometimes it comes very handy.

**Comment by torkelo** [comment]
This looks like a useful addition but it's built ontop of a breaking change  (https://github.com/grafana/simple-json-datasource/pull/103) which makes it tricky to merge

**Comment by rfogel** [comment]
Hello. I´m trying to pass addidition json data using variables like this:

**Comment by rfogel** [comment]
I'm already using this version. How can I achieve that? This code i shown gives json format error

**Comment by simPod** [comment]
Oh I see. "using variables" We're not parsing variables there yet unfortunately.

There's an issue already opened for that https://github.com/simPod/grafana-json-datasource/issues/11

**Comment by rfogel** [comment]
Ok, thanks for the information.

**Comment by simPod** [comment]
Hi @mankoffs, I intend to have such feature here. However, I'm currently busy with my work and finishing other OSS. I'll be able to look into it when I have a task concerning Grafana in my work. You can send PR, I will do review ASAP.

**Comment by simPod** [comment]
@mankoffs resolved in https://github.com/simPod/grafana-json-datasource/pull/26

**Pull request closed without merging**
