### PR TITLE
Allow to type long queries in editor mode

### PR DESCRIPTION
**Pull request by manuquentin**
To be able to send complex queries to the datasource, I propose to add an editor mode (like in the influxdb datasource).

It will be helpful when you have to type a mongodb query and you want to send it directly to the datasource, instead of selecting a metric.

Here a demo of the editor mode :
editor-mode

This PR fix also the handling of the `hide` attribute of each targets.

### CODE REVIEW

**Comment by shanielh** [comment]
Great! I was just looking to do this change too.

Hope it will be merged.

**Comment by manuquentin** [comment]
Hi,
Yes templates variables are replaced [here](https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js#L91).

This PR uses the same mechanism.

**Comment by bergquist** [comment]
Sounds like a good idea. I will look into this soon :)

**Comment by manuquentin** [comment]
Ok ! done

**Comment by bergquist** [comment]
@manuquentin thank you for contributing!

**Pull request merged**
