### PR TITLE
Timeseries

### PR DESCRIPTION
**Pull request by simPod**
Built on top of https://github.com/grafana/simple-json-datasource/pull/95

`Timeserie` is not a word https://ell.stackexchange.com/questions/23268/is-series-plural-or-singular/23271#23271

### CODE REVIEW

**Comment by andig** [comment]
It would be nice to make this consistent with e.g. the MySQL datasource:

	this.formats = [{ text: 'Time series', value: 'time_series' }, { text: 'Table', value: 'table' }];

	<select class="gf-form-input gf-size-auto" ng-model="ctrl.target.format" ng-options="f.value as f.text for f in ctrl.formats" ng-change="ctrl.refresh()"></select>

Renaming the value would obviously be a breaking change but does imho make sense for sake of readability.

**Comment by andig** [comment]
This PR is also implemented in https://github.com/simPod/grafana-json-datasource and can be closed here.

**Comment by andig** [comment]
Fixes #114

**Comment by Jonnymcc** [comment]
Why are there changes in the Gruntfile and package.json? They seem unrelated to changing "timeserie" to "timeseries".

**Comment by simPod** [comment]
Yup but it was split to commits that have clear message so it's just 👌 

However, we have maintained version at https://github.com/simpod/simple-json-datasource so closing this.

**Pull request closed without merging**
