### PR TITLE
Add "query" field

### PR DESCRIPTION
**Pull request by gmarsay**
Add a "query" field for data filtering in the json backend

### CODE REVIEW

**Comment by daniellee** [comment]
Why do you need an extra field for querying? What's wrong with the target field?

**Comment by gmarsay** [comment]
The target field return a list of metrics. With a query field i can send parameters on my datasource for to filter results.

Example: my datasource contains the columns "website" and "browser" and i want display all browsers of a single website.
The target field allow to select the column "browser" and the query field allow to filter on one or more websites.

**Comment by beyondkmp** [comment]
It is very useful. I can use template variable to select different  metrics.

**Comment by daniellee** [comment]
I am going to close this. If you want to add extra query fields then I think it is a good point to fork this project and create your own data source.

I think you have misunderstood how the target field works. The metricFindQuery function is what returns a list of parameters. But you can write anything in that field (see example below) as a query "target" parameter. The target parameter can take in any value and be used for filtering. I understand that you might have a use case where you want multiple fields for creating queries but we want to keep this plugin very simple.

image

**Pull request closed without merging**
